// app-react/src/components/AppDescription.jsx
function AppDescription() {
    return (
        <div className="row">
            <div id="appDescription" className="card">
                <p>
                    O aplicativo Fipe por Fipe foi desenvolvido para quem quer pesquisar
                    os valores de veículos da tabela Fipe e fazer comparações entre
                    esses valores.
                    <br/>
                    <br/>
                    O processamento do aplicativo gera dois resultados:
                    <br/>
                    - O valor da diferença entre os preços dos veículos (maior - menor)
                    <br/>
                    - Um gráfico com os valores para melhor visualização
                    <br/>
                    <br/>
                    O comparativo é um diferencial exclusivo do app Fipe por Fipe, que
                    foi feito pensando nos negociadores de veículos novos e usados, onde
                    é comum ouvir a expressão "Fipe por Fipe", quando os valores da
                    tabela oficial da Fipe serão considerados numa negociação de
                    veículos.
                    <br/>
                    <br/>
                    O aplicativo utiliza a API disponibilizada pelo site <a href="https://www.tabelafipebrasil.com/api/"
                        target="_blank" rel="noreferrer">TabelaFipeBrasil</a>, o
                    que garante os preços atualizados em tempo real com a última tabela
                    disponível no <a href="https://veiculos.fipe.org.br/" target="_blank" rel="noreferrer">site oficial da Fipe</a>.
                </p>
            </div>
        </div>
    )
}

export default AppDescription;

// app/src/components/AppDescription.vue
<template>
    <div class="row">
            <div id="appDescription" class="card">
                <p>
                    O aplicativo Fipe por Fipe foi desenvolvido para quem quer pesquisar
                    os valores de veículos da tabela Fipe e fazer comparações entre
                    esses valores.
                    <br>
                    <br>
                    O processamento do aplicativo gera dois resultados:
                    <br>
                    - O valor da diferença entre os preços dos veículos (maior - menor)
                    <br>
                    - Um gráfico com os valores para melhor visualização
                    <br>
                    <br>
                    O comparativo é um diferencial exclusivo do app Fipe por Fipe, que
                    foi feito pensando nos negociadores de veículos novos e usados, onde
                    é comum ouvir a expressão "Fipe por Fipe", quando os valores da
                    tabela oficial da Fipe serão considerados numa negociação de
                    veículos.
                    <br>
                    <br>
                    O aplicativo utiliza a API disponibilizada pelo site <a href="https://www.tabelafipebrasil.com/api/"
                        target="_blank">TabelaFipeBrasil</a>, o
                    que garante os preços atualizados em tempo real com a última tabela
                    disponível no <a href="https://veiculos.fipe.org.br/" target="_blank">site oficial da Fipe</a>.
                </p>
            </div>
        </div>
</template>
